name: dismissible_page
description: Creates page that is dismissed by swipe gestures, with Hero style animations, Inspired by FB, IG stories.
version: 0.6.1
homepage: https://github.com/Tkko/Flutter_dismissible_page
repository: https://github.com/Tkko/Flutter_dismissible_page

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.9.0

